
server:
  port: 18080

spring:
  datasource:
    username: alex
    password: zjy00322
    url: jdbc:mysql://127.0.0.1/ncov?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #thymeleaf start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    suffix: .html
    cache: false

    # Redis 配置
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:

      # 连接池最大连接数（使用负值表示没有限制）
      pool.max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: -1
      # 连接池中的最大空闲连接
      pool.max-idle: 8
      # 连接池中的最小空闲连接
      pool.min-idle: 0
      # 连接超时时间（毫秒）
      pool.timeout: 1200
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.zjut.azhen.ncov.bean

#showSql
logging:
  level:
    com.zjut.azhen.ncov:
      mapping : debug